services:
  astrojs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: syringe-mobile-web-app
    pull_policy: build
    restart: always
    labels:
      # Traefik configuration discovery
      # https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels
      - "traefik.enable=true"
      - "traefik.http.middlewares.syringe-mobile-web-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.syringe-mobile-web-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.syringe-mobile-web-http.middlewares=syringe-mobile-web-redirect"
      - "traefik.http.routers.syringe-mobile-web-http.rule=Host(`syringeapp.docchula.com`)"
      - "traefik.http.routers.syringe-mobile-web-http.entrypoints=web"
      - "traefik.http.routers.syringe-mobile-web-https.rule=Host(`syringeapp.docchula.com`)"
      - "traefik.http.routers.syringe-mobile-web-https.entrypoints=websecure"
      - "traefik.http.routers.syringe-mobile-web-https.tls.certresolver=leresolver"
      - "traefik.http.services.syringe-mobile-web-https.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G